# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4733e96784b6a0a4eb72b8ea77fe4fa93362390f585df7a7583141d0423753a3a72238c957316307a0716da177eb467a1c8efa1c6255924d1b70226321a6abef

test:
  secret_key_base: 87c19ac891746733c094d8d0f0a7c0e59be36210ebb99db5893f8e96e512f0bf2e0875c5c1f07af5fe4551928c858b84e32ea5309d3bcd580c2aee60e7464f2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
